"""Random Rule Forest.

An interpretable ensemble framework for binary classification based on YES/NO questions
generated by LLMs.
"""

from ._rrf import RRF, QuestionExclusion
from ._types import EmbeddingModel, AnsSimilarityFunc
from ._cost_sensitive import CostSensitiveConfig
from ._prompt_presets import PromptPreset, PROMPT_PRESETS, VC_FOUNDER_PRESET
from ._cross_validation import cross_validate_aggregation, CVResult

__all__ = [
    "RRF",
    "QuestionExclusion",
    "EmbeddingModel",
    "AnsSimilarityFunc",
    "CostSensitiveConfig",
    "PromptPreset",
    "PROMPT_PRESETS",
    "VC_FOUNDER_PRESET",
    "cross_validate_aggregation",
    "CVResult",
]
